# FROM node:22-alpine
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# RUN adduser -D nodeuser && chown -R nodeuser:nodeuser /app
# USER nodeuser
# ENV NODE_ENV=development
# EXPOSE 5173
# CMD ["npm", "run", "dev"]


# Build stage
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

