services:  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5050:5050"
    environment:
      NODE_ENV: development
      MONGODB_DEBUG: true
      LOGSTASH_HOST: logstash
      HOSTNAME: dibolky-backend
    networks:
      multi_net:   
        aliases:
          - dibolky
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      logstash:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5050/api/health"]
      interval: 90s
      timeout: 10s
      retries: 3
      start_period: 90s
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://172.19.0.5:12201"
        tag: "backend"
        gelf-compression-type: "none"
    labels:
      project: Dibolky

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      multi_net:
        aliases:
          - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      project: Dibolky

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.1
    container_name: logstash
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5044:5044"
      - "12201:12201/udp"
      - "9600:9600"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      multi_net:
        aliases:
          - logstash
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9600"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    labels:
      project: Dibolky

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      multi_net:
        aliases:
          - kibana
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    labels:
      project: Dibolky

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      multi_net:
        aliases:
          - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      project: Dibolky

networks:
  multi_net:
    external: true
    labels:
      project: Dibolky

volumes:
  redis_data:
    driver: local
    labels:
      project: Dibolky
  es_data:
    driver: local
    labels:
      project: Dibolky
  frontend_builds:
    external: true
