FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN adduser -D nodeuser && chown -R nodeuser:nodeuser /app
USER nodeuser
ENV NODE_ENV=development
EXPOSE 5050
CMD ["npm", "run", "dev", "start"]



