name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy on VM
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.VM_SSH_USER }}@${{ secrets.VM_INSTANCE_IP }} << 'EOF'
            set -e
            cd /opt/projects/Dibolky
            git pull origin main

            echo "Stopping current Docker Compose services..."
            sudo docker compose stop

            echo "Cleaning old Docker resources..."
            sudo docker ps -a --filter "label=project=Dibolky" -q | xargs -r sudo docker rm -f
            sudo docker images --filter "label=project=Dibolky" -q | xargs -r sudo docker rmi -f
            sudo docker volume ls --filter "label=project=Dibolky" -q | xargs -r sudo docker volume rm -f
            sudo docker network ls --filter "label=project=Dibolky" -q | xargs -r sudo docker network rm -f

            echo "Rebuilding and starting containers..."
            sudo docker compose up --build -d

            echo "Deployment complete!"
          EOF
