name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_INSTANCE_IP }} >> ~/.ssh/known_hosts

    - name: Deploy on GCE VM
      run: |
        ssh ${{ secrets.VM_SSH_USER }}@${{ secrets.VM_INSTANCE_IP }} << 'EOF'
          cd /opt/projects/Dibolky
          sudo git pull origin main
          sudo docker container stop 
          docker ps -a --filter "label=project=Dibolky" -q | xargs -r docker rm -f
          docker images --filter "label=project=Dibolky" -q | xargs -r docker rmi -f
          docker volume ls --filter "label=project=Dibolky" -q | xargs -r docker volume rm -f
          docker network ls --filter "label=project=Dibolky" -q | xargs -r docker network rm -f
          sudo docker compose up --build -d 
        EOF
