name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VM_SSH_PRIVATE_KEY }}

      - name: Add VM to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VM_INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Deploy on VM
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.VM_SSH_USER }}@${{ secrets.VM_INSTANCE_IP }} << 'EOF'
            set -e
            cd /opt/projects/Dibolky
            git pull origin main

            echo "Installing dependencies and building frontend..."
            cd frontend
            npm install
            npm run build

            echo "Moving build to shared volume (frontend_builds)..."
            mkdir -p /var/lib/docker/volumes/frontend_builds/_data/dibolky
            cp -r dist/* /var/lib/docker/volumes/frontend_builds/_data/dibolky/

            echo "Stopping current Docker Compose services..."
            sudo docker compose stop

            echo "Cleaning old Docker resources..."
            sudo docker ps -a --filter "label=project=Dibolky" -q | xargs -r sudo docker rm -f
            sudo docker images --filter "label=project=Dibolky" -q | xargs -r sudo docker rmi -f
            sudo docker volume ls --filter "label=project=Dibolky" -q | xargs -r sudo docker volume rm -f
            sudo docker network ls --filter "label=project=Dibolky" -q | xargs -r sudo docker network rm -f

            echo "Rebuilding and starting containers..."
            sudo docker compose up --build -d

            echo "Deployment complete!"
          EOF
